project:
  type: website

website:
  title: "website_test"
  navbar:
    # background: primary
    # search: true
    left:
      # what to do click on home
      - href: README.html
        text: Dashboard
      - about.qmd
      - README.qmd
      - index.qmd
      # - talks.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


