# This file was generated by the {rix} R package v0.6.0 on 2024-02-27
# with following call:
# >rix::rix(r_ver = "8520c158aee718c6e87b56881105fc4223c3c723",
#  > r_pkgs = c(pkgs_dev,
#  > pkgs_proj),
#  > system_pkgs = c("quarto",
#  > "radianWrapper",
#  > "oh-my-zsh",
#  > "nano",
#  > "openssl")[1:5],
#  > git_pkgs = list(list(package_name = "rsims",
#  > repo_url = "https://github.com/Robot-Wealth/rsims/",
#  > branch_name = "main",
#  > commit = "5ecb5cb2cc113d0b420f18a3329ee52e283f84c0"),
#  > list(package_name = "rix",
#  > repo_url = "https://github.com/b-rodrigues/rix",
#  > branch_name = "master",
#  > commit = "6dcc9bcb10dcd1baaa9a7d83bab5d1445f231455")),
#  >      ide = c("code",
#  > "rstudio")[1],
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = c("",
#  > tar_make = "Rscript -e 'targets::tar_make()'",
#  > radian = "radian")[1])
# It uses nixpkgs' revision 8520c158aee718c6e87b56881105fc4223c3c723 for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/8520c158aee718c6e87b56881105fc4223c3c723.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) devtools dplyr fs ggplot2 goodpractice pacman purrr quarto readr stringr tarchetypes targets tibble tidyr visNetwork glue here lmtest lubridate patchwork roll sandwich tibbletime tidyfit languageserver;
};
 git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
    name = "rsims";
    src = pkgs.fetchgit {
      url = "https://github.com/Robot-Wealth/rsims/";
      branchName = "main";
      rev = "5ecb5cb2cc113d0b420f18a3329ee52e283f84c0";
      sha256 = "sha256-USKhpYbNMNkiGweMCUZsGW1Ad3KQ9GBj0txn442GBkQ=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) dplyr tibble tidyr stringr magrittr ggplot2 lubridate here roll Rcpp;
    };
  })
(pkgs.rPackages.buildRPackage {
    name = "rix";
    src = pkgs.fetchgit {
      url = "https://github.com/b-rodrigues/rix";
      branchName = "master";
      rev = "6dcc9bcb10dcd1baaa9a7d83bab5d1445f231455";
      sha256 = "sha256-Gn0R4ND4AHE8wjtEEyHFI4Gl0p39nlb26VLRW16kClU=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) codetools httr jsonlite sys;
    };
  }) ];
  system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix quarto radianWrapper oh-my-zsh nano openssl;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ git_archive_pkgs rpkgs  system_packages  ];
      
  }
