# This file was generated by the {rix} R package v0.6.0 on 2024-02-28
# with following call:
# >rix::rix(r_ver = "9c1ea5e3a2a2578792438cba233f2763593e19c5",
#  > r_pkgs = c(pkgs_dev,
#  > pkgs_proj),
#  > system_pkgs = c("quarto",
#  > "radianWrapper",
#  > "oh-my-zsh",
#  > "nano",
#  > "openssl",
#  > "lazygit",
#  > "clang",
#  > "gcc"),
#  > git_pkgs = list(list(package_name = "rsims",
#  > repo_url = "https://github.com/Robot-Wealth/rsims/",
#  > branch_name = "main",
#  > commit = "5ecb5cb2cc113d0b420f18a3329ee52e283f84c0"),
#  > list(package_name = "rix",
#  > repo_url = "https://github.com/b-rodrigues/rix",
#  > branch_name = "master",
#  > commit = "6dcc9bcb10dcd1baaa9a7d83bab5d1445f231455")),
#  >      ide = c("code",
#  > "rstudio")[1],
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = c("",
#  > "\n        Rscript -e '{\n          pacman::p_load(targets,
#  > here,
#  > dplyr)\n          # FIXME: got to be a better way!\n          scr <- as.character(quote(exp_ret_mdl.R))\n          str <- as.character(quote(exp_ret_mdl_store))\n          targets::tar_config_set(\n            script = scr,
#  > store = str)\n          targets::tar_make(\n            callr_function = NULL\n          )}' ; radian\n      ",
#  >          "radian")[2])
# It uses nixpkgs' revision 9c1ea5e3a2a2578792438cba233f2763593e19c5 for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/9c1ea5e3a2a2578792438cba233f2763593e19c5.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) devtools dplyr fs ggplot2 goodpractice pacman purrr quarto readr stringr tarchetypes targets tibble tidyr visNetwork glue here lmtest lubridate patchwork roll sandwich tibbletime tidyfit languageserver;
};
 git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
    name = "rsims";
    src = pkgs.fetchgit {
      url = "https://github.com/Robot-Wealth/rsims/";
      branchName = "main";
      rev = "5ecb5cb2cc113d0b420f18a3329ee52e283f84c0";
      sha256 = "sha256-USKhpYbNMNkiGweMCUZsGW1Ad3KQ9GBj0txn442GBkQ=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) dplyr tibble tidyr stringr magrittr ggplot2 lubridate here roll Rcpp;
    };
  })
(pkgs.rPackages.buildRPackage {
    name = "rix";
    src = pkgs.fetchgit {
      url = "https://github.com/b-rodrigues/rix";
      branchName = "master";
      rev = "6dcc9bcb10dcd1baaa9a7d83bab5d1445f231455";
      sha256 = "sha256-Gn0R4ND4AHE8wjtEEyHFI4Gl0p39nlb26VLRW16kClU=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) codetools httr jsonlite sys;
    };
  }) ];
  system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix quarto radianWrapper oh-my-zsh nano openssl lazygit clang gcc;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ git_archive_pkgs rpkgs  system_packages  ];
      shellHook = "
        Rscript -e '{
          pacman::p_load(targets, here, dplyr)
          # FIXME: got to be a better way!
          scr <- as.character(quote(exp_ret_mdl.R))
          str <- as.character(quote(exp_ret_mdl_store))
          targets::tar_config_set(
            script = scr, store = str)
          targets::tar_make(
            callr_function = NULL
          )}' ; radian
      ";
  }
