FROM ghcr.io/xtruder/nix-devcontainer:v1

#FROM nixos/nix:latest AS builder

#RUN nix \
#    --extra-experimental-features "nix-command flakes" \
#    --option filter-syscalls false \
#     build
# RUN nix-shell -p R radianWrapper rPackages.ggplot2 rPackages.pacman 
# R glibcLocales nix cairo lazygit nano oh-my-zsh openssl quarto radianWrapper

# FROM mcr.microsoft.com/devcontainers/javascript-node:0-18
# RUN export DEBIAN_FRONTEND=noninteractive
#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install git


# CMD nix-shell -p 'rWrapper.override{packages = [ rPackages.rix ] ; } '
# CMD ["bash"]
